import '../../features/listas/domain/categoria.dart';

/// Dicionário estático local de categorias (spec F6 §4, ADR-011): termo em
/// pt-BR (minúsculo, sem acento) → categoria. O match casa quando TODAS as
/// palavras do termo aparecem como palavras do nome do item; entradas de
/// mais palavras casam antes das de uma ("leite condensado" vence "leite").
/// Não cobre tudo — o que não casa vai para `outros` e passa a ser lembrado
/// pela memória por nome (lib/core/categorias/sugestao_categorias.dart).
const Map<String, CategoriaItem> dicionarioCategorias = {
  // ---- hortifruti ----
  'banana': CategoriaItem.hortifruti,
  'maça': CategoriaItem.hortifruti,
  'laranja': CategoriaItem.hortifruti,
  'limão': CategoriaItem.hortifruti,
  'tomate': CategoriaItem.hortifruti,
  'cebola': CategoriaItem.hortifruti,
  'alho': CategoriaItem.hortifruti,
  'batata': CategoriaItem.hortifruti,
  'batata doce': CategoriaItem.hortifruti,
  'cenoura': CategoriaItem.hortifruti,
  'alface': CategoriaItem.hortifruti,
  'couve': CategoriaItem.hortifruti,
  'rúcula': CategoriaItem.hortifruti,
  'espinafre': CategoriaItem.hortifruti,
  'brócolis': CategoriaItem.hortifruti,
  'couve flor': CategoriaItem.hortifruti,
  'abóbora': CategoriaItem.hortifruti,
  'abobrinha': CategoriaItem.hortifruti,
  'berinjela': CategoriaItem.hortifruti,
  'pepino': CategoriaItem.hortifruti,
  'pimentão': CategoriaItem.hortifruti,
  'vagem': CategoriaItem.hortifruti,
  'milho verde': CategoriaItem.hortifruti,
  'manga': CategoriaItem.hortifruti,
  'mamão': CategoriaItem.hortifruti,
  'abacaxi': CategoriaItem.hortifruti,
  'melancia': CategoriaItem.hortifruti,
  'melão': CategoriaItem.hortifruti,
  'uva': CategoriaItem.hortifruti,
  'pera': CategoriaItem.hortifruti,
  'pêssego': CategoriaItem.hortifruti,
  'ameixa': CategoriaItem.hortifruti,
  'kiwi': CategoriaItem.hortifruti,
  'morango': CategoriaItem.hortifruti,
  'cereja': CategoriaItem.hortifruti,
  'goiaba': CategoriaItem.hortifruti,
  'maracujá': CategoriaItem.hortifruti,
  'caju': CategoriaItem.hortifruti,
  'tangerina': CategoriaItem.hortifruti,
  'lima': CategoriaItem.hortifruti,
  'gengibre': CategoriaItem.hortifruti,
  'salsa': CategoriaItem.hortifruti,
  'cebolinha': CategoriaItem.hortifruti,
  'coentro': CategoriaItem.hortifruti,
  'manjericão': CategoriaItem.hortifruti,
  'alho poró': CategoriaItem.hortifruti,
  'rabanete': CategoriaItem.hortifruti,
  'beterraba': CategoriaItem.hortifruti,
  'chuchu': CategoriaItem.hortifruti,
  'mandioca': CategoriaItem.hortifruti,
  'macaxeira': CategoriaItem.hortifruti,
  'inhame': CategoriaItem.hortifruti,
  'cogumelo': CategoriaItem.hortifruti,
  'abacate': CategoriaItem.hortifruti,
  // ---- mercearia ----
  'arroz': CategoriaItem.mercearia,
  'feijão': CategoriaItem.mercearia,
  'macarrão': CategoriaItem.mercearia,
  'espaguete': CategoriaItem.mercearia,
  'açúcar': CategoriaItem.mercearia,
  'sal': CategoriaItem.mercearia,
  'farinha': CategoriaItem.mercearia,
  'fubá': CategoriaItem.mercearia,
  'polvilho': CategoriaItem.mercearia,
  'tapioca': CategoriaItem.mercearia,
  'café': CategoriaItem.mercearia,
  'chá': CategoriaItem.mercearia,
  'mate': CategoriaItem.mercearia,
  'óleo': CategoriaItem.mercearia,
  'azeite': CategoriaItem.mercearia,
  'vinagre': CategoriaItem.mercearia,
  'azeitona': CategoriaItem.mercearia,
  'atum': CategoriaItem.mercearia,
  'sardinha': CategoriaItem.mercearia,
  'milho': CategoriaItem.mercearia,
  'ervilha': CategoriaItem.mercearia,
  'extrato de tomate': CategoriaItem.mercearia,
  'molho de tomate': CategoriaItem.mercearia,
  'mostarda': CategoriaItem.mercearia,
  'ketchup': CategoriaItem.mercearia,
  'maionese': CategoriaItem.mercearia,
  'shoyu': CategoriaItem.mercearia,
  'molho inglês': CategoriaItem.mercearia,
  'caldo': CategoriaItem.mercearia,
  'biscoito': CategoriaItem.mercearia,
  'bolacha': CategoriaItem.mercearia,
  'cereal': CategoriaItem.mercearia,
  'aveia': CategoriaItem.mercearia,
  'granola': CategoriaItem.mercearia,
  'chocolate': CategoriaItem.mercearia,
  'cacau': CategoriaItem.mercearia,
  'farofa': CategoriaItem.mercearia,
  'paçoca': CategoriaItem.mercearia,
  'goiabada': CategoriaItem.mercearia,
  'geleia': CategoriaItem.mercearia,
  'mel': CategoriaItem.mercearia,
  'leite condensado': CategoriaItem.mercearia,
  'creme de leite': CategoriaItem.mercearia,
  'granulado': CategoriaItem.mercearia,
  'pipoca': CategoriaItem.mercearia,
  'fermento': CategoriaItem.mercearia,
  'gelatina': CategoriaItem.mercearia,
  'amido': CategoriaItem.mercearia,
  'lentilha': CategoriaItem.mercearia,
  'grão de bico': CategoriaItem.mercearia,
  // ---- frios (proteínas e fatiados de balcão) ----
  'queijo': CategoriaItem.frios,
  'presunto': CategoriaItem.frios,
  'mortadela': CategoriaItem.frios,
  'salame': CategoriaItem.frios,
  'pepperoni': CategoriaItem.frios,
  'bacon': CategoriaItem.frios,
  'linguiça': CategoriaItem.frios,
  'calabresa': CategoriaItem.frios,
  'salsicha': CategoriaItem.frios,
  'carne': CategoriaItem.frios,
  'bife': CategoriaItem.frios,
  'picanha': CategoriaItem.frios,
  'costela': CategoriaItem.frios,
  'frango': CategoriaItem.frios,
  'peito de frango': CategoriaItem.frios,
  'asa de frango': CategoriaItem.frios,
  'coxa de frango': CategoriaItem.frios,
  'file de frango': CategoriaItem.frios,
  'peixe': CategoriaItem.frios,
  'tilápia': CategoriaItem.frios,
  'salmão': CategoriaItem.frios,
  'camarão': CategoriaItem.frios,
  'ovo': CategoriaItem.frios,
  'ovos': CategoriaItem.frios,
  // ---- laticínios ----
  'leite': CategoriaItem.laticinios,
  'iogurte': CategoriaItem.laticinios,
  'manteiga': CategoriaItem.laticinios,
  'margarina': CategoriaItem.laticinios,
  'requeijão': CategoriaItem.laticinios,
  'queijo cottage': CategoriaItem.laticinios,
  'coalhada': CategoriaItem.laticinios,
  'kefir': CategoriaItem.laticinios,
  // ---- congelados ----
  'sorvete': CategoriaItem.congelados,
  'pizza': CategoriaItem.congelados,
  'lasanha congelada': CategoriaItem.congelados,
  'hambúrguer': CategoriaItem.congelados,
  'nuggets': CategoriaItem.congelados,
  'batata congelada': CategoriaItem.congelados,
  'legumes congelados': CategoriaItem.congelados,
  'picolé': CategoriaItem.congelados,
  // ---- padaria ----
  'pão': CategoriaItem.padaria,
  'pão francês': CategoriaItem.padaria,
  'pão de queijo': CategoriaItem.padaria,
  'pão integral': CategoriaItem.padaria,
  'baguete': CategoriaItem.padaria,
  'rosca': CategoriaItem.padaria,
  'bolo': CategoriaItem.padaria,
  'bisnaga': CategoriaItem.padaria,
  'torrada': CategoriaItem.padaria,
  // ---- bebidas ----
  'água': CategoriaItem.bebidas,
  'água mineral': CategoriaItem.bebidas,
  'água com gás': CategoriaItem.bebidas,
  'refrigerante': CategoriaItem.bebidas,
  'coca': CategoriaItem.bebidas,
  'guaraná': CategoriaItem.bebidas,
  'suco': CategoriaItem.bebidas,
  'néctar': CategoriaItem.bebidas,
  'cerveja': CategoriaItem.bebidas,
  'vinho': CategoriaItem.bebidas,
  'espumante': CategoriaItem.bebidas,
  'vodka': CategoriaItem.bebidas,
  'whisky': CategoriaItem.bebidas,
  'cachaça': CategoriaItem.bebidas,
  'energético': CategoriaItem.bebidas,
  'isotônico': CategoriaItem.bebidas,
  'chá gelado': CategoriaItem.bebidas,
  // ---- pet ----
  'ração': CategoriaItem.pet,
  'areia de gato': CategoriaItem.pet,
  'biscoito de cachorro': CategoriaItem.pet,
  'petisco': CategoriaItem.pet,
  'coleira': CategoriaItem.pet,
  'arranhador': CategoriaItem.pet,
  'areia higiênica': CategoriaItem.pet,
  // ---- limpeza ----
  'detergente': CategoriaItem.limpeza,
  'sabão': CategoriaItem.limpeza,
  'sabão em pó': CategoriaItem.limpeza,
  'saponário': CategoriaItem.limpeza,
  'água sanitária': CategoriaItem.limpeza,
  'alvejante': CategoriaItem.limpeza,
  'amaciante': CategoriaItem.limpeza,
  'cloro': CategoriaItem.limpeza,
  'desinfetante': CategoriaItem.limpeza,
  'limpador': CategoriaItem.limpeza,
  'multiuso': CategoriaItem.limpeza,
  'esponja': CategoriaItem.limpeza,
  'palha de aço': CategoriaItem.limpeza,
  'saco de lixo': CategoriaItem.limpeza,
  'sacola': CategoriaItem.limpeza,
  'limpa vidro': CategoriaItem.limpeza,
  'inseticida': CategoriaItem.limpeza,
  'naftalina': CategoriaItem.limpeza,
  'vassoura': CategoriaItem.limpeza,
  'rodo': CategoriaItem.limpeza,
  'pano de chão': CategoriaItem.limpeza,
  'desentupidor': CategoriaItem.limpeza,
  // ---- higiene ----
  'sabonete': CategoriaItem.higiene,
  'shampoo': CategoriaItem.higiene,
  'condicionador': CategoriaItem.higiene,
  'pasta de dente': CategoriaItem.higiene,
  'escova de dente': CategoriaItem.higiene,
  'fio dental': CategoriaItem.higiene,
  'papel higiênico': CategoriaItem.higiene,
  'absorvente': CategoriaItem.higiene,
  'fralda': CategoriaItem.higiene,
  'lenço de papel': CategoriaItem.higiene,
  'desodorante': CategoriaItem.higiene,
  'desodorante roll-on': CategoriaItem.higiene,
  'creme': CategoriaItem.higiene,
  'algodão': CategoriaItem.higiene,
  'curativo': CategoriaItem.higiene,
  'esparadrapo': CategoriaItem.higiene,
  'gilete': CategoriaItem.higiene,
  'lâmina': CategoriaItem.higiene,
  'protetor solar': CategoriaItem.higiene,
  'fralda geriátrica': CategoriaItem.higiene,
  'lencinho': CategoriaItem.higiene,
};
